/**
 * Locale-aware utilities: filename/label helpers, language names, and footer.
 * Pulls locale strings through t() internally — consumers still import t()
 * directly from ./strings when they need the translation interface.
 */

import { t } from "./strings";

// ---------------------------------------------------------------------------
// Filename / label suffix helpers
// ---------------------------------------------------------------------------

/** Build a locale-suffixed report filename. English uses no suffix. */
export const resolveFilename = (base: string, lang = "en"): string =>
  lang === "en" ? `${base}.md` : `${base}.${lang}.md`;

/** Build a locale-suffixed GitHub issue label. English uses no suffix. */
export const resolveLabel = (base: string, lang = "en"): string => (lang === "en" ? base : `${base}-${lang}`);

// ---------------------------------------------------------------------------
// Auto-generated footer
// ---------------------------------------------------------------------------

export const autoGenFooter = (lang = "en"): string => {
  const digestRepo = process.env["DIGEST_REPO"] ?? "";
  if (!digestRepo) return "";
  const localized = t(lang).autoGenFooter;
  if (localized) return `\n\n---\n*${localized}*`;
  return `\n\n---\n*This digest is auto-generated by [Big Model Radar](https://github.com/${digestRepo}).*`;
};
